In [1]:
import pandas as pd

In [2]:
pd.__file__

'/workspaces/docker-training/pipeline/.venv/lib/python3.13/site-packages/pandas/__init__.py'

In [3]:
prefix = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/'
url = f'{prefix}/yellow_tripdata_2021-01.csv.gz'
url

'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow//yellow_tripdata_2021-01.csv.gz'

In [4]:
df = pd.read_csv(url)

/tmp/ipykernel_7326/4176769558.py:1: DtypeWarning: Columns (0: store_and_fwd_flag) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(url)

In [5]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1.0,2021-01-01 00:30:10,2021-01-01 00:36:12,1.0,2.10,1.0,N,142,43,2.0,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1.0,2021-01-01 00:51:20,2021-01-01 00:52:19,1.0,0.20,1.0,N,238,151,2.0,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1.0,2021-01-01 00:43:30,2021-01-01 01:11:06,1.0,14.70,1.0,N,132,165,1.0,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1.0,2021-01-01 00:15:48,2021-01-01 00:31:01,0.0,10.60,1.0,N,138,132,1.0,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2.0,2021-01-01 00:31:49,2021-01-01 00:48:21,1.0,4.94,1.0,N,68,33,1.0,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5

In [6]:
df.dtypes

VendorID                 float64
tpep_pickup_datetime         str
tpep_dropoff_datetime        str
passenger_count          float64
trip_distance            float64
RatecodeID               float64
store_and_fwd_flag           str
PULocationID               int64
DOLocationID               int64
payment_type             float64
fare_amount              float64
extra                    float64
mta_tax                  float64
tip_amount               float64
tolls_amount             float64
improvement_surcharge    float64
total_amount             float64
congestion_surcharge     float64
dtype: object

In [7]:
df.shape

(1369765, 18)

In [8]:
dtype = {
    "VendorID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "string",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "payment_type": "Int64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "congestion_surcharge": "float64"
}

parse_dates = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]

df = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates
)

In [9]:
!uv add sqlalchemy

Resolved 118 packages in 0.79ms
Checked 9 packages in 0.21ms

In [10]:
!uv add psycopg2-binary

Resolved 118 packages in 0.81ms
Checked 9 packages in 0.23ms

In [11]:
from sqlalchemy import create_engine
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [12]:
print(pd.io.sql.get_schema(df, name='yellow_taxi_data',con= engine))

CREATE TABLE yellow_taxi_data (
	"VendorID" BIGINT,
	tpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	tpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	"RatecodeID" BIGINT,
	store_and_fwd_flag TEXT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	payment_type BIGINT,
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	congestion_surcharge FLOAT(53)
)

In [ ]:
# This is to create a table with no data and just heaader

In [13]:
df.head(n=0).to_sql(name='yellow_taxi_data', con=engine, if_exists='replace')

0

In [13]:
print(pd.io.sql.get_schema(df, name='yellow_taxi_data',con= engine))

CREATE TABLE yellow_taxi_data (
	"VendorID" BIGINT,
	tpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	tpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	"RatecodeID" BIGINT,
	store_and_fwd_flag TEXT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	payment_type BIGINT,
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	congestion_surcharge FLOAT(53)
)

In [16]:
len(df)

1369765

In [ ]:
# Now the data has beennn created

In [17]:
df_iter = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates,
    iterator=True,
    chunksize=100000
)

In [18]:
df_iter

In [ ]:
# This is to make the datasets pump into postgreSQL

In [19]:
df = next(df_iter)

In [20]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1,2021-01-01 00:57:42,2021-01-01 01:08:18,1,3.10,1,N,264,264,1,11.5,0.5,0.5,1.00,0.0,0.3,13.80,0.0
996,2,2021-01-01 00:19:34,2021-01-01 00:31:34,1,2.77,1,N,170,239,1,11.0,0.5,0.5,2.96,0.0,0.3,17.76,2.5
997,2,2021-01-01 00:16:38,2021-01-01 00:24:23,3,2.01,1,N,41,263,1,8.5,0.5,0.5,2.46,0.0,0.3,14.76,2.5
998,2,2021-01-01 00:28:09,2021-01-01 00:40:08,1,3.35,1,N,263,186,4,-12.0,-0.5,-0.5,0.00,0.0,-0.3,-15.80,-2.5
999,2,2021-01-01 00:28:09,2021-01-01 00:40:08,1,3.35,1,N,263,186,2,12.0,0.5,0.5,0.00,0.0,0.3,15.80,2.5

In [21]:
!uv add tqdm

Resolved 119 packages in 256ms
Prepared 1 package in 29ms
░░░░░░░░░░░░░░░░░░░░ [0/1] Installing wheels...                                 warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 1 package in 15ms
 + tqdm==4.67.3

In [22]:
from tqdm.auto import tqdm

In [ ]:
# We can make a fool loop instead

In [25]:
for df_chunk in tqdm(df_iter):
    df_chunk.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')

0it [00:00, ?it/s]